weberp/apps/expenses/urls.py
from django.conf.urls import url
from . import views
app_name = 'expenses'

urlpatterns = [
    url(r'^$', views.ExpenseListView.as_view(), name='expenses_list')
]

weberp/apps/incomes/urls.py
from django.conf.urls import url
from . import views
app_name = 'incomes'

urlpatterns = [
    url(r'^$', views.IncomeListView.as_view(), name='incomes_list')
]

weberp/apps/stats/urls.py
from django.conf.urls import url

from . import views
app_name = 'stats'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index')
]

weberp/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.stats.urls', namespace='stats')),
    url(r'^contractors/', include('apps.contractors.urls', namespace='contractors')),
    url(r'^products/', include('apps.products.urls', namespace='products')),
    url(r'^expenses/', include('apps.expenses.urls', namespace='expenses')),
    url(r'^incomes/', include('apps.incomes.urls', namespace='incomes')),
]

weberp/apps/stats/models.py
from django.db import models

# Create your models here.

weberp/apps/stats/views.py
# Create your views here.
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context

weberp/apps/stats/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Основная тема проекта, используется bootstrap3 -->
    <meta http-equiv="Content-Type" content="text/html" ; charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Блок для добавления css файлов в проект -->
    {% block additional_css %}
    {% endblock %}

    <!-- Блок для добавления js файлов в проект -->
    {% block additional_js %}
    {% endblock %}

    <title>
        {% block title %}
        {% endblock %} ERP
    </title>

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'stats:index' %}">Главная</a></li>
                    <li><a href="{% url 'expenses:expenses_list' %}">Записи расходов</a></li>
                    <li><a href="{% url 'incomes:incomes_list' %}">Записи доходов</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="indented"><a href="/admin/">Админ</a></li>
                </ul>
            </div>
        </nav>
        <!-- Блок для вставки основного контента в проект -->
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

weberp/apps/stats/templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    <h3>Главная страница</h3>
</div>


{% endblock %}